### PR TITLE
To do list request review!

### PR DESCRIPTION
**Pull request by AlexRS90**

### CODE REVIEW

**Comment by codepantha** [comment]
## Hi @AlexRS90 👋 
Your project looks great with some cool features.

### However, there are some changes which I would suggest based on best practices 👇

**Comment by codepantha** [comment]
- In this line of code below, the variable name `hola` which you intend to hold the values of the todo list items stored in the localStorage, and the key `lista` is not descriptive and is a little confusing. What do you think?
https://github.com/AlexRS90/to-do-list-rewiew/blob/2a573d0dc6b360ac03dff779e0b57d6cf1d28e27/src/dinamically.js#L10-L14
I would suggest you scrap the variable name entirely and condense the code into one line like this:
`listToDo = JSON.parse(localStorage.getItem('lista'));`

**Comment by codepantha** [comment]
- This function could have a name that properly describes what it does which is to save tasks to the `localStorage`. Something like `saveTask()` - what do you think? 🤔 
https://github.com/AlexRS90/to-do-list-rewiew/blob/2a573d0dc6b360ac03dff779e0b57d6cf1d28e27/src/dinamically.js#L6-L8

**Comment by codepantha** [comment]
- You have a very big function from `line 10` to `line 95`
https://github.com/AlexRS90/to-do-list-rewiew/blob/2a573d0dc6b360ac03dff779e0b57d6cf1d28e27/src/dinamically.js#L10-L15
Sticking with the KISS principle, the best practice would be to have a function that does only 1 thing. The function above does a lot of things and even contains whole new function declarations. What do you think about this observation? 💭

**Comment by AlexRS90** [comment]
Hi Promise!!
Thanks for your comment and suggestions, yes I agree with the names, I can improve it 😃

**Pull request merged**
